### ISSUE TITLE
Error in calculating Malayalam Year from Saka Year

### ISSUE THREAD

**Issue by floydpink** [kollavarsham/kollavarsham-nodejs#4]
[This gist](https://gist.github.com/floydpink/cfc9db1179e1409d446e) is the Malyalam calendar for 2015, which is the response from http://calendar.kollavarsham.org/api/years/2015 (with `Accept: plain/text` header)

And as can be seen there, for the few days in March and April (starting from [this line](https://gist.github.com/floydpink/cfc9db1179e1409d446e#file-2015-kollavarsham-calendar-L160)) the Malayalam year jumps one incorrectly.

This seems to be because 2015-March-21 is the beginning of a new year in the Saka Calendar and the `saura masa` (or malayalam month) has still not crossed into the next month to make the current version of the equation to calculate the Malyalam Year work:

Offending lines [at lines 110 and 111](https://github.com/kollavarsham/kollavarsham-nodejs/blob/master/lib/calculations.js#L110..L111) in `lib/calculations.js`:

```javascript
    var malayalamYear = globals.YearSaka - 747 +
      math.truncate((sauraMasaNum - globals.malayalaMasaNum + 12) / 12);
```

**Comment by arunkutty** [comment]
I have cloned calendar-api and updated kollavarsham-nodejs and reproduced the problem with my local server. I will check the code and let you know.

**Comment by floydpink** [comment]
:+1:

**Comment by arunkutty** [comment]
It is interesting to me that the same date shows the correct year when the CLI is used. I will continue looking. 

Aruns-MacBook-Pro:lib arun$ kollavarsham 21:03:2015

                          kollavarsham
   Based on the Pancanga Perl library by M. YANO and M. FUSHIMI
   http://www.cc.kyoto-su.ac.jp/~yanom/pancanga/message313.html
   ------------------------------------------------------------

You are trying to convert the Gregorian date 21:03:2015 to Kollavarsham date
Date is Sat Mar 21 2015 00:00:00 GMT+0530 (IST)

The current settings for kollavarsham calculations are as follows:
Bija           : false
Mode           : 0
Latitude       : 23.2
Longitude      : 75.8
Output         : verbose

Output
------
Saka : 1936	01 Phalguna   (11) 	[Suklapaksa]
Saura: 1936	07 Mina       (11) 	U-bhadrapada
ME   : 1190	07 Meenam     (07) 	Uthrattathi

Aruns-MacBook-Pro:lib arun$

**Comment by floydpink** [comment]
I just formatted your comment to show the console output as plain text.

Here is what I see here - and from the version that I can see on the banner: `kollavarsham (v0.2.2)`, which is missing in your output, I think you might be running an older version of the CLI?

```
hari@MacBook-Pro ~ $ kollavarsham 21:03:2015

              kollavarsham (v0.2.2)
   Based on the Pancanga Perl library by M. YANO and M. FUSHIMI
   http://www.cc.kyoto-su.ac.jp/~yanom/pancanga/message314.html
   ------------------------------------------------------------

You are trying to convert the Gregorian date 21:03:2015 to Kollavarsham date
Date is Sat Mar 21 2015 00:00:00 GMT-0400 (EDT)

The current settings for kollavarsham calculations are as follows:
System         : SuryaSiddhanta
Mode           : undefined
Latitude       : 23.2
Longitude      : 75.8
Output         : verbose

Output
------
Saka : 1937	01 Caitra     (00) 	[Suklapaksa]
Saura: 1937	07 Mina       (11) 	U-bhadrapada
ME   : 1191	07 Meenam     (07) 	Uthrattathi

hari@MacBook-Pro ~ $ kollavarsham 20:03:2015

              kollavarsham (v0.2.2)
   Based on the Pancanga Perl library by M. YANO and M. FUSHIMI
   http://www.cc.kyoto-su.ac.jp/~yanom/pancanga/message314.html
   ------------------------------------------------------------

You are trying to convert the Gregorian date 20:03:2015 to Kollavarsham date
Date is Fri Mar 20 2015 00:00:00 GMT-0400 (EDT)

The current settings for kollavarsham calculations are as follows:
System         : SuryaSiddhanta
Mode           : undefined
Latitude       : 23.2
Longitude      : 75.8
Output         : verbose

Output
------
Saka : 1936	15 Phalguna   (11) 	[Krsnapaksa]
Saura: 1936	06 Mina       (11) 	P-bhadrapada
ME   : 1190	06 Meenam     (07) 	Poororuttathi

hari@MacBook-Pro ~ $ 
```

**Comment by floydpink** [comment]
The version in banner has been added more than an year ago via this commit -  https://github.com/kollavarsham/kollavarsham-nodejs/commit/f0dc0ffa43858a1ec0ab6203442f4e3b02664405

It is interesting that it says `Bija           : false` on your output and on mine it says `System         : SuryaSiddhanta`

Could it really be a regression compared to the version that you are running to generate the correct output above? :smile:

**Comment by arunkutty** [comment]
I had pulled in your changes but **kollavarsham** which was in the path was being taken from /usr/local/bin/lib and it was a soft link to a cli.js that was installed globally long back. I can see the problem now like how you did.

**Comment by floydpink** [comment]
Okay great. 

Should we just give a try with that dated version within the API and see how that generates the year? What was the version on the older cli?

**Comment by arunkutty** [comment]
I added some debug prints on the older library as well as the latest code. This is how it looks like. 
```
Old code: 
malayalam year is 1190
sauraMasaNum is 11
malayalaMasaNum is 7
saka year is 1936
kali year is 5115
ahargana is 1868637
globals.masaNum is 11

Latest code:
malayalam year is 1191
sauraMasaNum is 11
malayalaMasaNum is 7
saka year is 1937
kali year is 5116
ahargana is 1868637.2516427054
globals.masaNum is 0
```
The old version gave the correct Malayalam year due to an incorrect Saka year calculated and not due to a better formula to calculate the Malayalam year from the Saka year. The Saka year calculated in the new version matches that given by Pancanga and so has to be accurate.

I think we should improve the Saka to Malayalam year conversion formula. I don't know how at this point and will continue investigating.

**Comment by arunkutty** [comment]
Looks like we have caught this one. The Saka year transitions to the new one on the basis of lunar month which is available in globals.masaNum. That being the case, globals.masaNum is a better candidate to find out the offset to calculate the Malayalam year than sauraMasaNum.
This version of the equation seems to be eliminating the problem. I checked for a few years. 
```
    var malayalamYear = globals.YearSaka - 747 +
      math.truncate((globals.masaNum - globals.malayalaMasaNum + 12) / 12);
```

**Comment by floydpink** [comment]
Fixed via https://github.com/kollavarsham/kollavarsham-nodejs/commit/0b3a81fba1db0bea3d18906be571c809fe94f573 :sparkles:
